language: objective-c
osx_image: xcode8
before_install:
- gem install xcpretty --no-document
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
script:
- pod lib lint
deploy:
  provider: script
  script: ./scripts/push.sh
  on:
    tags: true
